const std = @import("std");

/// Error codes for TypeScript compiler errors
pub const ErrorCode = enum(u32) {
    no_input_files = 1000,
    compile_file_not_found,
    output_write_failed,
    report_error_truncated,
    error_count_exceeds_max,
    no_project,
    non_project_files_are_in_list,
    invalid_config_file,
    can_not_find_config_file,
    invalid_file_name,
    unknown_compiler_option,
    empty_command_line_value,
    unknown_language_mode,
    file_text_changes_is_null,
    unsupported_file_reading,
    convert_color_to_hex_string,
    deprecated_write_file_tracks,
    emit_and_callback_error,
    tsconfig_invalid_option,
    json_source_text_too_long,
    duplicate_watched_directories,
    unsupported_read_options,
    diagnostic_code_exceeds_max,
    no_entry_point_provided,
    cannot_find_module,
    cannot_find_module_with_type,
    cannot_find_package,
    cannot_find_tsconfig,
    cannot_read_tsconfig,
    circular_alias,
    circular_resolve,
    alias_cannot_be_circular,
    unknown_property_with_type,
    type_does_not_exist,
    value_does_not_exist,
    unknown_type,
    unknown_symbol,
    duplicate_identifier,
    duplicate_identifiers_in_binder,
    identifier_not_found,
    import_cannot_be_resolved,
    import_cannot_be_written,
    file_cannot_be_written,
    no_symbol_found,
    no_definition_found,
    no_completion_found,
    no_navigation_found,
    no_tsconfig_path,
    no_refactor,
    no_suggestion,
    wrong_initialization_option,
    wrong_file_language_service,
    wrong_language_service_args,
    cannot_prepare_reorder,
    could_not_write_file,
    no_output,
    no_output_erased,
    not_all_outputs_written,
    incremental_mode_not_available,
    no_files_found,
    no_errors,
    cannot_read_file,
    no_project_references,
    process_exit_called,
    no_binder_options,
    no_complier_options,
    unknown_compiler_option_for_build,
    cannot_compile_with_isolated_modules,
    cannot_compile_with_out_dir,
    cannot_compile_without_strict,
    cannot_write_to_config_file,
    compiler_option_ambiguous,
    unknown_compiler_option_for_tsconfig,
    file_not_in_project,
    no_default_library,
    missing_file,
};

/// Error messages
pub const ErrorMessage = struct {
    code: ErrorCode,
    message: []const u8,
};

/// Error table
pub const ErrorTable = []const ErrorMessage;

pub const default_error_table = [_]ErrorMessage{
    .{ .code = .no_input_files, .message = "No input files were specified." },
    .{ .code = .cannot_find_module, .message = "Cannot find module '{0}'." },
    .{ .code = .cannot_find_tsconfig, .message = "Cannot find a tsconfig.json file at the current directory." },
    .{ .code = .circular_alias, .message = "Circular alias resolution." },
    .{ .code = .duplicate_identifier, .message = "Duplicate identifier '{0}'." },
    .{ .code = .file_not_in_project, .message = "File '{0}' is not in the project." },
};
